[package]
name = "hiramu-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive","cargo"] }
futures-util = "0.3.30"
hiramu = "0.1.9"
tokio = "1.37.0"
