name: hiramu-cli CI/CD Pipeline

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write

jobs:
  build-and-upload:
    name: Build and Upload Artifact
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: macos
            os: macos-11
            target: x86_64-apple-darwin
          - build: windows
            os: windows-2019
            target: x86_64-pc-windows-msvc
          - build: macos_arm64
            os: macos-11
            target: aarch64-apple-darwin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install OpenSSL via Homebrew (macOS only)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install openssl
          echo "OPENSSL_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV

      - name: Build Project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package Build Artifacts
        run: |
          binary_name="hiramu-cli"
          ref_name=$(echo "${GITHUB_REF}" | sed 's|refs/.*/||')
          dirname="${binary_name}-${ref_name}-${{ matrix.target }}"
          mkdir -p "$dirname"
          if [ "${{ matrix.os }}" == "windows-2019" ]; then
            mv "target/${{ matrix.target }}/release/${binary_name}.exe" "$dirname/"
            # Use PowerShell for compressing artifacts on Windows
            pwsh -Command "Compress-Archive -Path '$dirname/*' -DestinationPath '$dirname.zip'"
            echo "ASSET_PATH=$dirname.zip" >> $GITHUB_ENV
          else
            mv "target/${{ matrix.target }}/release/${binary_name}" "$dirname/"
            tar -czvf "$dirname.tar.gz" "$dirname"
            echo "ASSET_PATH=$dirname.tar.gz" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Extract Version from Cargo.toml
        id: cargo_toml_version
        run: |
          version=$(sed -n -e 's/^version = "\(.*\)"/\1/p' Cargo.toml)
          echo "::set-output name=version::$version"
        shell: bash

      - name: Delete local tag if exists
        run: |
          git tag -d v${{ steps.cargo_toml_version.outputs.version }} || true
        shell: bash

      - name: Delete remote tag if exists
        run: |
          git push --delete origin v${{ steps.cargo_toml_version.outputs.version }} || true
        shell: bash

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ steps.cargo_toml_version.outputs.version }} -m "Release v${{ steps.cargo_toml_version.outputs.version }}"
          git push origin v${{ steps.cargo_toml_version.outputs.version }}
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}